FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY src/ .

RUN dotnet build App.Api/App.Api.csproj -c Release -o release/

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS app
WORKDIR /app

COPY --from=build src/release/ .

ENV ASPNETCORE_URLS "http://*:80"
EXPOSE 80
ENTRYPOINT [ "dotnet", "Fwks.FwksApp.App.Api.dll" ]