FROM node:18-alpine AS build
WORKDIR /app

ARG ENVIRONMENT

COPY ui/ .

RUN npm install -g pnpm && \
    pnpm install && \
    npm run build-${ENVIRONMENT}

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80